[config]

# Defina aqui o tipo do envio das mensagens a serem enviadas.
#
# imagem : Para enviar imagens com ou sem texto
#
# ou
#
# texto : Para enviar apenas texto.
#
# padrão: imagem

tipo_msg=imagem

############################################################

# Defina aqui o tempo (em segundos) para abrir o WhatsApp Web e aguardar o carregamento

# (padrão: 20)

tempo=20

############################################################

# Defina aqui o tempo (em segundos) para fechar a aba do WhatsApp Web após o envio da mensagem

# (padrão: 3)

tempo_fechar=3

############################################################

# Defina aqui se a aba do WhatsApp Web deve ser fechada após o envio da mensagem

# padrão: True (para fechar)
#     
#         False (para não fechar. Várias abas ficarão abertas no navegador)

fechar=True